language: java
sudo: false
jobs:
  include:
      - stage: test
        script: "mvn clean test -f TineiMatewai"
      - stage: cobertura
        script: "mvn cobertura:cobertura -f TineiMatewai"
        after_success:
          - bash <(curl -s https://codecov.io/bash)
jdk:
  - oraclejdk11