language: java
sudo: false
jobs:
  include:
      - stage: Test and Coverage
        script: "mvn clean test -f TineiMatewai"
        after_success:
          - bash <(curl -s https://codecov.io/bash)
