language: java
os: linux
dist: trusty
cache:
  directories:
    - $HOME/.m2
jobs:
  include:
      - stage: Test and Coverage
        script: "mvn clean test -f TineiMatewai"
        after_success:
          - bash <(curl -s https://codecov.io/bash)
      - stage: Deploy Snapshot
        script: "cp .travis.settings.xml $HOME/.m2/.settings.xml && mvn clean deploy -DskipTests -f TineiMatewai"
        after_success:
          - bash <(curl -s https://codecov.io/bash)
