language: java
os: linux
dist: trusty
jobs:
  include:
      - stage: Test and Coverage
        script: "mvn clean test -f TineiMatewai"
        after_success:
          - bash <(curl -s https://codecov.io/bash)
      - stage: Deploy Snapshot
        script: "mvn --settings .travis.settings.xml clean deploy -DskipTests -f TineiMatewai"
      - stage: Deploy Release
        script: "mvn --settings .travis.settings.xml clean release:prepare release:perform --batch-mode -DskipTests -f TineiMatewai"
        branches:
          only:
            - master
